/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import classes.Despesas;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import servicos.ServicoDespesas;

/**
 *
 * @author Pichau
 */
public class FCadDespesas extends javax.swing.JFrame {

    /**
     * Creates new form FCadDespesas
     */
    public FCadDespesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jValor = new javax.swing.JTextField();
        jEnviarDespesas = new javax.swing.JButton();
        jTipoComboDespesa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDataPagamento = new javax.swing.JTextField();
        jDataPagamentoEsperado = new javax.swing.JTextField();
        jConta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorActionPerformed(evt);
            }
        });

        jEnviarDespesas.setText("Enviar");
        jEnviarDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEnviarDespesasMouseClicked(evt);
            }
        });
        jEnviarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnviarDespesasActionPerformed(evt);
            }
        });

        jTipoComboDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentacao", "Educacao", "Lazer", "Moradia", "Roupa", "Saude" }));
        jTipoComboDespesa.setSelectedIndex(-1);
        jTipoComboDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipoComboDespesaActionPerformed(evt);
            }
        });

        jLabel2.setText("Data  Pagamento");

        jLabel3.setText("Data  Pagamento Esperado");

        jLabel5.setText("Tipo Despesa");

        jDataPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataPagamentoActionPerformed(evt);
            }
        });

        jDataPagamentoEsperado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataPagamentoEsperadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor");

        jLabel9.setText("Conta");

        jSair.setText("Sair");
        jSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSairMouseClicked(evt);
            }
        });
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jEnviarDespesas)
                .addGap(18, 18, 18)
                .addComponent(jSair))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDataPagamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDataPagamentoEsperado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jConta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTipoComboDespesa, 0, 100, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jDataPagamentoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTipoComboDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEnviarDespesas)
                    .addComponent(jSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorActionPerformed

    private void jDataPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataPagamentoActionPerformed

    private void jDataPagamentoEsperadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataPagamentoEsperadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataPagamentoEsperadoActionPerformed

    private void jTipoComboDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipoComboDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTipoComboDespesaActionPerformed

    private void jEnviarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnviarDespesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEnviarDespesasActionPerformed

    private void jEnviarDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEnviarDespesasMouseClicked
        Despesas despesas = new Despesas();
       despesas.setValor(Float.parseFloat(jValor.getText()));
       despesas.setDataPagamento(jDataPagamento.getText());
       despesas.setDataPagamentoEsperado(jDataPagamentoEsperado.getText());
       despesas.setTipoDespesa(jTipoComboDespesa.getSelectedItem().toString());
       despesas.setConta(jConta.getText()) ; 
       ServicoDespesas servicodespesas = new ServicoDespesas();
         
        try {
            servicodespesas.insert(despesas);
            JOptionPane.showMessageDialog(rootPane, "Despesas Cadastradas");
            this.limparTela();
        } catch (SQLException ex) {
            Logger.getLogger(FCadDespesas.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_jEnviarDespesasMouseClicked
   
    private void jSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSairMouseClicked
           dispose();
    }//GEN-LAST:event_jSairMouseClicked

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        
    }//GEN-LAST:event_jSairActionPerformed

   public void limparTela(){
        jValor.setText("");
        jDataPagamento.setText("");
        jDataPagamentoEsperado.setText("");
        jTipoComboDespesa.setSelectedIndex(-1);
        jConta.setText(""); 
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCadDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCadDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCadDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCadDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCadDespesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jConta;
    private javax.swing.JTextField jDataPagamento;
    private javax.swing.JTextField jDataPagamentoEsperado;
    private javax.swing.JButton jEnviarDespesas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jSair;
    private javax.swing.JComboBox<String> jTipoComboDespesa;
    private javax.swing.JTextField jValor;
    // End of variables declaration//GEN-END:variables
}
