/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import classes.Receita;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import servicos.ServicoReceita;

/**
 *
 * @author Matheus
 */
public class FEditReceitas extends javax.swing.JFrame {

    ServicoReceita servicoreceita = new ServicoReceita();
    /**
     * Creates new form FEditReceitas
     */
    public FEditReceitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboReceita = new javax.swing.JComboBox<>();
        jDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboTipoReceita = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jValor = new javax.swing.JTextField();
        jDataRecebimento = new javax.swing.JTextField();
        jDataRecebimentoEsperado = new javax.swing.JTextField();
        jAtualizar = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Selecione a receita que você gostaria de editar");

        jComboReceita.setMaximumRowCount(10);
        jComboReceita.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboReceitaItemStateChanged(evt);
            }
        });

        jLabel2.setText("Valor");

        jComboTipoReceita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salario", "Presente", "Premio", "Outros" }));
        jComboTipoReceita.setSelectedIndex(-1);
        jComboTipoReceita.setAutoscrolls(true);
        jComboTipoReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoReceitaActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Recebimento Esperado");

        jLabel4.setText("Data Recebimento");

        jLabel5.setText("Descricao");

        jLabel7.setText("Tipo Receita");

        jAtualizar.setText("Atualizar");
        jAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAtualizarMouseClicked(evt);
            }
        });

        jDelete.setText("Deletar");
        jDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDeleteMouseClicked(evt);
            }
        });
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jSair.setText("Sair");
        jSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAtualizar)
                                .addGap(35, 35, 35)
                                .addComponent(jDelete)
                                .addGap(18, 18, 18)
                                .addComponent(jSair)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(129, 129, 129)
                                .addComponent(jComboTipoReceita, 0, 236, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboReceita, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jDataRecebimentoEsperado, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                        .addComponent(jDataRecebimento)
                                        .addComponent(jValor))
                                    .addComponent(jDescricao))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jDataRecebimentoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboTipoReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAtualizar)
                    .addComponent(jDelete)
                    .addComponent(jSair))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            this.atualizarListaReceita();

        } catch (SQLException ex) {
            Logger.getLogger(FEditReceitas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jComboReceitaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboReceitaItemStateChanged
        if (jComboReceita.getItemCount() <= 0){
            return;
        }
        
        if (jComboReceita.getSelectedIndex() < 0){
            return;
        } 
        
        Receita receita = (Receita) jComboReceita.getSelectedItem();
        jValor.setText(String.valueOf(receita.getValor()));
        jDataRecebimento.setText(receita.getDataRecebimento());
        jDataRecebimentoEsperado.setText(receita.getDataRecebimentoEsperado());
        jDescricao.setText(receita.getDescricao());
        jComboTipoReceita.setSelectedItem(receita.getTipoReceitas());

    }//GEN-LAST:event_jComboReceitaItemStateChanged

    private void jComboTipoReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoReceitaActionPerformed

    private void jAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAtualizarMouseClicked
        if (jComboReceita.getSelectedIndex() >= 0){
            Receita receita = (Receita) jComboReceita.getSelectedItem();
            receita.setDataRecebimento(jDataRecebimento.getText());
            receita.setDataRecebimentoEsperado(jDataRecebimentoEsperado.getText());
            receita.setDescricao(jDescricao.getText());
            receita.setTipoReceitas(jComboTipoReceita.getSelectedItem().toString());
            receita.setValor(Float.parseFloat(jValor.getText()));
            try {
                servicoreceita.update(receita);
                JOptionPane.showMessageDialog(rootPane, "Conta atualizada com sucesso!!");
                this.limparTela();
            } catch (SQLException ex) {
                Logger.getLogger(FEditReceitas.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
   
    }//GEN-LAST:event_jAtualizarMouseClicked

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDeleteMouseClicked
        if (jComboReceita.getSelectedIndex() >= 0){
            Receita receita = (Receita) jComboReceita.getSelectedItem();
            try {
                servicoreceita.delete(receita);
                JOptionPane.showMessageDialog(rootPane, "Receita deletada!!");
            } catch (SQLException ex) {
                Logger.getLogger(FEditReceitas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }//GEN-LAST:event_jDeleteMouseClicked

    private void jSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSairMouseClicked
        dispose();
    }//GEN-LAST:event_jSairMouseClicked
    
    private void atualizarListaReceita() throws SQLException{
        if (jComboReceita.getItemCount() > 0){
            jComboReceita.removeAllItems();
        }

        ArrayList<Receita> lista = servicoreceita.getListaReceita();   
        for (Receita u:lista){
               jComboReceita.addItem(u);
        }      
        this.limparTela();
     }
    
    
    public void limparTela(){
        jValor.setText("");
        jDataRecebimento.setText("");
        jDataRecebimentoEsperado.setText("");
        jDescricao.setText("");
        jComboReceita.setSelectedIndex(-1);
        jComboTipoReceita.setSelectedIndex(-1);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEditReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEditReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEditReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEditReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEditReceitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAtualizar;
    private javax.swing.JComboBox<Receita> jComboReceita;
    private javax.swing.JComboBox<String> jComboTipoReceita;
    private javax.swing.JTextField jDataRecebimento;
    private javax.swing.JTextField jDataRecebimentoEsperado;
    private javax.swing.JButton jDelete;
    private javax.swing.JTextField jDescricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jSair;
    private javax.swing.JTextField jValor;
    // End of variables declaration//GEN-END:variables
}
