/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import classes.Contas;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import servicos.ServicoContas;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class FEditContas extends javax.swing.JFrame {

    ServicoContas servicocontas = new ServicoContas();
    /**
     * Creates new form FEditContas
     */
    public FEditContas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboContas = new javax.swing.JComboBox<>();
        jSaldo = new javax.swing.JTextField();
        jInstituicaoFinanceira = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboTipoContas = new javax.swing.JComboBox<>();
        jAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jComboContas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboContasItemStateChanged(evt);
            }
        });

        jSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaldoActionPerformed(evt);
            }
        });

        jInstituicaoFinanceira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInstituicaoFinanceiraActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo Contas");

        jLabel3.setText("Instituicao Financeira");

        jLabel4.setText("Saldo");

        jComboTipoContas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carteira", "Conta Corrente", "Poupanca" }));
        jComboTipoContas.setSelectedIndex(-1);
        jComboTipoContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoContasActionPerformed(evt);
            }
        });

        jAtualizar.setText("Atualizar");
        jAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAtualizarMouseClicked(evt);
            }
        });

        jLabel1.setText("                                  Selecione a conta que deseja atualizar");

        jDelete.setText("Deletar");
        jDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDeleteMouseClicked(evt);
            }
        });
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboContas, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInstituicaoFinanceira, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboTipoContas, javax.swing.GroupLayout.Alignment.TRAILING, 0, 200, Short.MAX_VALUE)
                    .addComponent(jSaldo, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jAtualizar)
                        .addGap(30, 30, 30)
                        .addComponent(jDelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTipoContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInstituicaoFinanceira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAtualizar)
                    .addComponent(jDelete))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSaldoActionPerformed

    private void jInstituicaoFinanceiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInstituicaoFinanceiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInstituicaoFinanceiraActionPerformed

    private void jComboTipoContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoContasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoContasActionPerformed

    private void jAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAtualizarMouseClicked
        if (jComboContas.getSelectedIndex() >= 0){
            Contas contas = (Contas) jComboContas.getSelectedItem();
            contas.setSaldo(Float.parseFloat(jSaldo.getText()));
            contas.setTipoContas(jComboTipoContas.getSelectedItem().toString());
            contas.setInstituicaoFinanceira(jInstituicaoFinanceira.getText());
           

           try {
                servicocontas.update(contas);
                JOptionPane.showMessageDialog(rootPane, "Conta atualizada com sucesso!!");
                this.limparTela();
           } catch (SQLException ex) {
               Logger.getLogger(FEditDespesas.class.getName()).log(Level.SEVERE, null, ex);
           }
     
        }
        
    }//GEN-LAST:event_jAtualizarMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
        try {
            this.atualizarListaContas();
            jComboContas.setSelectedIndex(-1);
        } catch (SQLException ex) {
            Logger.getLogger(FEditContas.class.getName()).log(Level.SEVERE, null, ex);
        }

      
    }//GEN-LAST:event_formWindowActivated

    private void jComboContasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboContasItemStateChanged
       if (jComboContas.getItemCount() <= 0){
            return;
        }
        
        if (jComboContas.getSelectedIndex() < 0){
            return;
        } 
        
        Contas contas = (Contas) jComboContas.getSelectedItem();
        jSaldo.setText(String.valueOf(contas.getSaldo()));
        jComboTipoContas.setSelectedItem(contas.getTipoContas());
        jInstituicaoFinanceira.setText(contas.getInstituicaoFinanceira());   
    }//GEN-LAST:event_jComboContasItemStateChanged

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDeleteMouseClicked
       if (jComboContas.getSelectedIndex() >= 0){
            Contas contas = (Contas) jComboContas.getSelectedItem();
            try {
                servicocontas.delete(contas);
                JOptionPane.showMessageDialog(rootPane, "Contas deletadas!!");
            } catch (SQLException ex) {
                Logger.getLogger(FEditContas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jDeleteMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEditContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEditContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEditContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEditContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEditContas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAtualizar;
    private javax.swing.JComboBox<Contas> jComboContas;
    private javax.swing.JComboBox<String> jComboTipoContas;
    private javax.swing.JButton jDelete;
    private javax.swing.JTextField jInstituicaoFinanceira;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jSaldo;
    // End of variables declaration//GEN-END:variables

    private void atualizarListaContas() throws SQLException {
         if (jComboContas.getItemCount() > 0){
            jComboContas.removeAllItems();
        }

        ArrayList<Contas> lista = servicocontas.getListaContas();   
        for (Contas u:lista){
               jComboContas.addItem(u);
        }      
        this.limparTela();
    }
    
    public void limparTela(){
        jSaldo.setText("");
        jComboTipoContas.setSelectedIndex(-1);
        jInstituicaoFinanceira.setText("");     
    }
    
}
