/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import classes.Contas;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import servicos.ServicoContas;

/**
 *
 * @author Pichau
 */
public class FTransferencias extends javax.swing.JFrame {

    /**
     * Creates new form FTransferencias
     */
    public FTransferencias() {
        initComponents();
    }
    
    ServicoContas servicocontas = new ServicoContas();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboOrigem = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboDestino = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jValor = new javax.swing.JTextField();
        jTransferir = new javax.swing.JButton();
        jSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Selecione a conta de origem");

        jComboOrigem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboOrigemItemStateChanged(evt);
            }
        });

        jLabel2.setText("Selecione a conta de destino");

        jLabel3.setText("Digite o valor");

        jTransferir.setText("Transferir");
        jTransferir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTransferirMouseClicked(evt);
            }
        });

        jSair.setText("Sair");
        jSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSairMouseClicked(evt);
            }
        });
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboOrigem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTransferir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTransferir)
                    .addComponent(jSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSairActionPerformed

    private void jTransferirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTransferirMouseClicked
        if (jComboOrigem.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(rootPane, "Voce precisa selecionar uma conta de origem");
        }else{
            if(jComboDestino.getSelectedIndex() < 0){
                JOptionPane.showMessageDialog(rootPane, "Voce precisa selecionar uma conta de destino");
            }
        }
        
        Contas contadestino = (Contas) jComboDestino.getSelectedItem();  
        Contas contaorigem = (Contas) jComboOrigem.getSelectedItem(); 

        try {
            servicocontas.transferirOrigem(contaorigem, Float.parseFloat(jValor.getText()));
            servicocontas.transferirDestino(contadestino, Float.parseFloat(jValor.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(FTransferencias.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.limparTela();
        jValor.setText("");
        
    }//GEN-LAST:event_jTransferirMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            this.atualizarListaContas();
            jComboOrigem.setSelectedIndex(-1);
        } catch (SQLException ex) {
            Logger.getLogger(FTransferencias.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jComboOrigemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboOrigemItemStateChanged

        try {
            this.atualizarListaContasDestino();
            jComboDestino.removeItem(jComboOrigem.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(FTransferencias.class.getName()).log(Level.SEVERE, null, ex);
        }       
       
    }//GEN-LAST:event_jComboOrigemItemStateChanged

    private void jSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSairMouseClicked
        dispose();
    }//GEN-LAST:event_jSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTransferencias().setVisible(true);
            }
        });
    }
    
    private void atualizarListaContas() throws SQLException {
        if (jComboOrigem.getItemCount() > 0){
            jComboOrigem.removeAllItems();
        }

        ArrayList<Contas> lista = servicocontas.getListaContas();   
        for (Contas u:lista){
               jComboOrigem.addItem(u);
        }      
        this.limparTela();
    }
  
    private void atualizarListaContasDestino() throws SQLException {
        if (jComboDestino.getItemCount() > 0){
            jComboDestino.removeAllItems();
        }

        ArrayList<Contas> lista = servicocontas.getListaContas();   
        for (Contas u:lista){
               jComboDestino.addItem(u);
        }      

        
        
        jComboDestino.setSelectedIndex(-1);
        
    }
    
    public void limparTela(){
        jComboDestino.setSelectedIndex(-1);
        jComboOrigem.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Contas> jComboDestino;
    private javax.swing.JComboBox<Contas> jComboOrigem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jSair;
    private javax.swing.JButton jTransferir;
    private javax.swing.JTextField jValor;
    // End of variables declaration//GEN-END:variables
}
